---
- name: Check if the nginx config file is modified 
  hosts: Laboratorio  
  sources:
    - ansible.eda.url_check:
        urls:
          - http://192.168.3.2:8080
        delay: 5
  rules:
    - name: Run the action if the /usr/local/etc/nginx/nginx.conf is modified
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: Plantilla_prueba
          organization: Default
